### ISSUE TITLE
Question: how to inject script into page?

### ISSUE THREAD

**Issue by craft37** [mistakster/grunt-svg2string#2]
Please help to include compiled SVG-JS 

- Placed compiled JS into header
- the only var is SVG_SPRITE_SYMBOL in this js
- compiled SVGs was symnols so I requests to it via (early with full url to not-translated .svg icons appeared)
```
<svg class="icon">
              <use xlink:href="SVG_SPRITE_SYMBOL#app--images--icons--facebook" /></use>
 </svg>
```
But no result
- placed it into header, but also no icons:
```
<script type="text/javascript">
        document.getElementById('app--images--icons--facebook').innerHTML = SVG_SPRITE_SYMBOL;
  </script>
```
- empty div on page also exist
```
<div id="app--images--icons--facebook"
  style="border: 0; clip: rect(0 0 0 0); overflow: hidden;
    margin: -1px; padding: 0; position: absolute;
    width: 1px; height: 1px;">
</div>
```

Thanks!

**Comment by mistakster** [comment]
Could you provide gist or codepen, please. Also, could you show your Grunt config? It will help a lot. 

Thanks.

**Comment by craft37** [comment]
Aha, I've just runned placer-script before div. That was the trick.

All clear now. Seems I just can hide empty div with display:none.

Thanks for great tool.
